export const Levels = {
  one: 0,
  two: 1,
  tree: 2,
};

export const LevelsDictionary = new Map([
  [Levels.one, { name: "One" }],
  [Levels.two, { name: "Two" }],
  [Levels.tree, { name: "Tree" }],
]);

const IrregularVerbs = [
  {
    infinitive: "become",
    simple: "became",
    participle: "become",
    level: 0,
    translation: "стали",
  },
  {
    infinitive: "begin",
    simple: "began",
    participle: "begun",
    level: 0,
    translation: "начать",
  },
  {
    infinitive: "break",
    simple: "broke",
    participle: "broken",
    level: 0,
    translation: "сломать",
  },
  {
    infinitive: "bring",
    simple: "brought",
    participle: "brought",
    level: 0,
    translation: "принести",
  },
  {
    infinitive: "build",
    simple: "built",
    participle: "built",
    level: 0,
    translation: "строить",
  },
  {
    infinitive: "buy",
    simple: "bought",
    participle: "bought",
    level: 0,
    translation: "купить",
  },
  {
    infinitive: "catch",
    simple: "caught",
    participle: "caught",
    level: 0,
    translation: "поймать",
  },
  {
    infinitive: "choose",
    simple: "chose",
    participle: "chosen",
    level: 0,
    translation: "выберите",
  },
  {
    infinitive: "come",
    simple: "came",
    participle: "come",
    level: 0,
    translation: "прийти",
  },
  {
    infinitive: "cost",
    simple: "cost",
    participle: "cost",
    level: 0,
    translation: "стоимость",
  },
  {
    infinitive: "cut",
    simple: "cut",
    participle: "cut",
    level: 0,
    translation: "вырезать",
  },
  {
    infinitive: "do",
    simple: "did",
    participle: "done",
    level: 0,
    translation: "делать",
  },
  {
    infinitive: "draw",
    simple: "drew",
    participle: "drawn",
    level: 0,
    translation: "рисовать",
  },
  {
    infinitive: "drink",
    simple: "drank",
    participle: "drunk",
    level: 0,
    translation: "пить",
  },
  {
    infinitive: "drive",
    simple: "drove",
    participle: "driven",
    level: 0,
    translation: "водить(машину)",
  },
  {
    infinitive: "eat",
    simple: "ate",
    participle: "eaten",
    level: 0,
    translation: "есть",
  },
  {
    infinitive: "fall",
    simple: "fell",
    participle: "fallen",
    level: 0,
    translation: "падать",
  },
  {
    infinitive: "feed",
    simple: "fed",
    participle: "fed",
    level: 0,
    translation: "кормить",
  },
  {
    infinitive: "feel",
    simple: "felt",
    participle: "felt",
    level: 0,
    translation: "чувствовать",
  },
  {
    infinitive: "fight",
    simple: "fought",
    participle: "fought",
    level: 0,
    translation: "бороться",
  },
  {
    infinitive: "find",
    simple: "found",
    participle: "found",
    level: 0,
    translation: "находить",
  },
  {
    infinitive: "fly",
    simple: "flew",
    participle: "flown",
    level: 0,
    translation: "летать",
  },
  {
    infinitive: "forget",
    simple: "forgot",
    participle: "forgotten",
    level: 0,
    translation: "забыть",
  },
  {
    infinitive: "forgive",
    simple: "forgave",
    participle: "forgiven",
    level: 0,
    translation: "простить",
  },
  {
    infinitive: "get",
    simple: "got",
    participle: "gotten",
    level: 0,
    translation: "получить",
  },
  {
    infinitive: "give",
    simple: "gave",
    participle: "given",
    level: 0,
    translation: "давать",
  },
  {
    infinitive: "go",
    simple: "went",
    participle: "gone",
    level: 0,
    translation: "идти",
  },
  {
    infinitive: "grow",
    simple: "grew",
    participle: "grown",
    level: 0,
    translation: "расти",
  },
  {
    infinitive: "have",
    simple: "had",
    participle: "had",
    level: 0,
    translation: "иметь",
  },
  {
    infinitive: "hear",
    simple: "heard",
    participle: "heard",
    level: 0,
    translation: "слышать",
  },
  {
    infinitive: "hide",
    simple: "hid",
    participle: "hidden",
    level: 0,
    translation: "скрывать",
  },
  {
    infinitive: "hit",
    simple: "hit",
    participle: "hit",
    level: 0,
    translation: "бить",
  },
  {
    infinitive: "hold",
    simple: "held",
    participle: "held",
    level: 0,
    translation: "держать/удерживать",
  },
  {
    infinitive: "know",
    simple: "knew",
    participle: "known",
    level: 0,
    translation: "знать",
  },
  {
    infinitive: "learn",
    simple: "learned",
    participle: "learned",
    level: 0,
    translation: "учиться",
  },
  {
    infinitive: "leave",
    simple: "left",
    participle: "left",
    level: 0,
    translation: "покидать",
  },
  {
    infinitive: "lend",
    simple: "lent",
    participle: "lent",
    level: 0,
    translation: "давать в долг",
  },
  {
    infinitive: "lose",
    simple: "lost",
    participle: "lost",
    level: 0,
    translation: "терять",
  },
  {
    infinitive: "make",
    simple: "made",
    participle: "made",
    level: 0,
    translation: "сделать",
  },
  {
    infinitive: "mean",
    simple: "meant",
    participle: "meant",
    level: 0,
    translation: "означать",
  },
  {
    infinitive: "meet",
    simple: "met",
    participle: "met",
    level: 0,
    translation: "встречаться",
  },
  {
    infinitive: "pay",
    simple: "paid",
    participle: "paid",
    level: 0,
    translation: "платить",
  },
  {
    infinitive: "put",
    simple: "put",
    participle: "put",
    level: 0,
    translation: "положить",
  },
  {
    infinitive: "read",
    simple: "read",
    participle: "read",
    level: 0,
    translation: "читать",
  },
  {
    infinitive: "ride",
    simple: "rode",
    participle: "ridden",
    level: 0,
    translation: "ездить",
  },
  {
    infinitive: "rise",
    simple: "rose",
    participle: "risen",
    level: 0,
    translation: "подниматься",
  },
  {
    infinitive: "run",
    simple: "ran",
    participle: "run",
    level: 0,
    translation: "бежать",
  },
  {
    infinitive: "say",
    simple: "said",
    participle: "said",
    level: 0,
    translation: "сказать",
  },
  {
    infinitive: "see",
    simple: "saw",
    participle: "seen",
    level: 0,
    translation: "видеть",
  },
  {
    infinitive: "sell",
    simple: "sold",
    participle: "sold",
    level: 0,
    translation: "продавать",
  },
  {
    infinitive: "send",
    simple: "sent",
    participle: "sent",
    level: 0,
    translation: "отправить",
  },
  {
    infinitive: "set",
    simple: "set",
    participle: "set",
    level: 0,
    translation: "установить",
  },
  {
    infinitive: "show",
    simple: "showed",
    participle: "shown",
    level: 0,
    translation: "показать",
  },
  {
    infinitive: "sing",
    simple: "sang",
    participle: "sung",
    level: 0,
    translation: "петь",
  },
  {
    infinitive: "sit",
    simple: "sat",
    participle: "sat",
    level: 0,
    translation: "сидеть",
  },
  {
    infinitive: "sleep",
    simple: "slept",
    participle: "slept",
    level: 0,
    translation: "спать",
  },
  {
    infinitive: "speak",
    simple: "spoke",
    participle: "spoken",
    level: 0,
    translation: "разговаривать",
  },
  {
    infinitive: "spend",
    simple: "spent",
    participle: "spent",
    level: 0,
    translation: "проводить",
  },
  {
    infinitive: "stand",
    simple: "stood",
    participle: "stood",
    level: 0,
    translation: "стоять",
  },
  {
    infinitive: "steal",
    simple: "stole",
    participle: "stolen",
    level: 0,
    translation: "украсть",
  },
  {
    infinitive: "swim",
    simple: "swam",
    participle: "swum",
    level: 0,
    translation: "плавать",
  },
  {
    infinitive: "take",
    simple: "took",
    participle: "taken",
    level: 0,
    translation: "взять",
  },
  {
    infinitive: "teach",
    simple: "taught",
    participle: "taught",
    level: 0,
    translation: "учить",
  },
  {
    infinitive: "tell",
    simple: "told",
    participle: "told",
    level: 0,
    translation: "рассказать",
  },
  {
    infinitive: "think",
    simple: "thought",
    participle: "thought",
    level: 0,
    translation: "считать",
  },
  {
    infinitive: "throw",
    simple: "threw",
    participle: "thrown",
    level: 0,
    translation: "бросить",
  },
  {
    infinitive: "understand",
    simple: "understood",
    participle: "understood",
    level: 0,
    translation: "понять",
  },
  {
    infinitive: "wear",
    simple: "wore",
    participle: "worn",
    level: 0,
    translation: "носить",
  },
  {
    infinitive: "win",
    simple: "won",
    participle: "won",
    level: 0,
    translation: "выиграть",
  },
  {
    infinitive: "write",
    simple: "wrote",
    participle: "written",
    level: 0,
    translation: "записывать",
  },
];

export default IrregularVerbs;
